"""apply_rev3_restatement.py — rev3 of the Technovation manuscript: restatement on the non-empty corpus.

Applies exact, paragraph-level replacements (the rev2 method: no tracked changes, no comments, core
properties untouched) to the rev2 .docx files and writes rev3 files plus a machine-generated change log.
Every edit is keyed to a finding of the consistency report (§9.1) or the restated analysis (§12).

Usage:
    python -m src.manuscript.apply_rev3_restatement --src <corrections_20260822 dir> --out <corrections_20260823 dir> --ts YYYYMMDD_HHMMSS
"""
from __future__ import annotations
import argparse, copy, json, hashlib
from pathlib import Path
from docx import Document

# ---------------------------------------------------------------------------------------------------------------
# Edits: kind = para (replace whole paragraph found by prefix) | sub (replace substring within a paragraph found by
# prefix) | cell (table located by header text; row, col; new text) | note_after_table (new paragraph after a table,
# formatted like a template paragraph) | add_row (copy last row of a table and fill)
# ---------------------------------------------------------------------------------------------------------------
E = []
def para(id_, section, prefix, new, basis): E.append(dict(id=id_, section=section, kind="para", prefix=prefix, new=new, basis=basis))
def sub(id_, section, prefix, old, new, basis): E.append(dict(id=id_, section=section, kind="sub", prefix=prefix, old=old, new=new, basis=basis))
def cell(id_, section, header, row, col, new, basis): E.append(dict(id=id_, section=section, kind="cell", header=header, row=row, col=col, new=new, basis=basis))

para("E01", "Abstract", "Artificial intelligence (AI) increasingly supports",
 "Artificial intelligence (AI) increasingly supports innovation activities, yet research has focused on firm-level adoption, business models, and ideation systems, leaving the micro-level design of user research instruments under-examined. This paper investigates how interview-assisted AI and synthetic users can be mobilised to develop a stress-tested interview guide for maternity-care user research. Drawing on the knowledge-based view, AI-enabled synthetic user research is conceptualised as a knowledge-creation capability through which organisations expand and structure user knowledge before engaging real participants. In a synthetic design laboratory, 150 composite maternity personas were constructed, five candidate guide versions were generated, and 355 AI-mediated synthetic interviews were conducted under a balanced incomplete block design. On the 200 main-phase sessions unaffected by a provider failure, guide structure produced small but significant differences in conversational yield (composite richness 3.97–4.12 on a five-point scale) and large differences in insight yield (insights-to-needs ratios 12.6–27.0). An audit of the laboratory’s logs showed that its blind-spot diagnostics were constrained by the persona encoding and that the revised guide had not been administered, so the effect of diagnostics-driven revision remains untested; researcher-led consolidation produced the final twelve-question guide, corroborated against published maternal-health evidence and codified instrument-design standards. The paper offers a theoretical conceptualisation of AI-enabled synthetic user research as a front-end innovation capability, a replicable and auditable instrument-development methodology whose audit trail made its own failures detectable, and managerial guidance for embedding synthetic testing in innovation infrastructure in high-stakes services.",
 "Restated analysis §12; consistency report §9.1 items 1–3")
para("E02", "3.2.1", "The persona space was designed",
 "The persona space was designed to reflect the complexity of the maternity journey across preconception, pregnancy, birth, and post-partum. The personas varied in socio-demographic background, clinical risk, care pathway, and contextual conditions. In addition, they encoded nine latent experiential dimensions identified as theoretically relevant — autonomy versus dependence, trust and distrust in providers, power dynamics, structural barriers, informal care networks, identity tensions, emotional labour of care, knowledge asymmetry, and temporal pressure — six of which belong to the set of twelve canonical dimensions tracked in the coverage analysis (Section 4.3). The remaining six canonical dimensions (dignity and respect, continuity of care, partner role, digital information seeking, body image autonomy, and intergenerational patterns) were tracked in evaluation but not encoded in the personas, a distinction whose consequences are reported in Section 4.3. These persona specifications defined the synthetic design space within which candidate interview guides were stress-tested.",
 "Consistency report F5 and §9.1 item 3")
para("E03", "3.2.3", "The candidate instruments were stress-tested",
 "The candidate instruments were stress-tested through synthetic interviews. In each session a model instance adopted the synthetic participant profile, while the interviewer was a deterministic agent that administered the relevant instrument version verbatim — questions in order, probes by a word-count rule, at most three probes per question — so that differences between sessions could be attributed to the instrument and the persona rather than to interviewer behaviour. In this way, AI-mediated interviews were generated under controlled prompt conditions, and full logs of prompts, outputs, and versioning decisions were retained. The main phase was preceded by a calibration pilot (sixteen planned sessions across four personas) used to calibrate the persona role; in the classification of its transcripts, thirteen of sixteen extracted statements (81.25%) expressed latent insights rather than surface-level needs, and the calibrated role prompts were frozen for the main runs.",
 "Consistency report §9.1 item 6 (interviewer) and F4 (pilot)")
sub("E04", "3.2.5", "After one candidate version had been taken forward",
 "The resulting instrument, V4_R1, constituted the final stress-tested guide.",
 "The resulting instrument, V4_R1, was intended as the final stress-tested guide; Section 4.4 reports that, owing to two implementation defects found in a post-hoc audit, the re-administration round did not administer the revised items.",
 "Consistency report §9.1 item 2")
sub("E05", "3.4", "Second, a codified-standards audit",
 "The audit and retrieval scripts (standards_audit.py; concordance_scopus.py) are included in the reproducibility package described in the data availability statement.",
 "The audit script (standards_audit.py), which recomputes Table 6 from the guide as printed in Appendix A, and the retrieval script (concordance_scopus.py), which resolves the sources that codify the audited criteria and builds their concordance, are included in the reproducibility package described in the data availability statement; the per-dimension literature anchors of Table 5 were assembled by the research team from the sources cited there.",
 "Consistency report §3 (scope of concordance_scopus.py)")
para("E06", "4.1", "The corpus was assessed along two analytical axes",
 "The corpus was assessed along two analytical axes. Conversational quality was scored on the 6,458 question-response pairs of the 300 main transcripts, and insight yield was classified across the full 355-session corpus of 7,403 question-response pairs. A post-hoc audit of the scoring outputs established that the 100 main-phase sessions whose persona was voiced by one of the three providers returned no text — the provider consumed its output-token allowance before emitting a response — so that 1,611 scored responses (24.9%) were empty strings scored 0. All figures in Sections 4.1–4.4 are therefore reported on the non-empty corpus: the 200 sessions voiced by the other two providers (35, 40, 38, 43 and 44 sessions for V1–V5) and their 4,816 scored responses; the figures computed on the full corpus, and the restatement script, are in the reproducibility package. Each response was rated on five independent dimensions—emotional depth, specificity, latent-dimension surfacing, narrative quality, and clinical grounding—each anchored on a 0–5 scale. A response’s composite richness was calculated as the mean of these five dimensions, and the reported corpus figure is the grand mean across all scored responses.",
 "Consistency report §9.1 item 1; restated analysis §1")
para("E07", "4.1", "On this basis, the main corpus achieved",
 "On this basis, the non-empty corpus achieved a mean composite richness of 4.06, indicating high yield. The dimension profile was uneven: emotional depth (4.41) and latent-dimension surfacing (4.36) were strongest, narrative quality (4.16) and specificity (3.93) were intermediate, and clinical grounding (3.44) was weakest, reflecting the difficulty of eliciting clinically specific details from synthetic respondents.",
 "Restated analysis §2")
para("E08", "4.1", "These results were generated through",
 "These results were generated through a deliberately cost-efficient, multi-provider configuration in which the synthetic-persona agents were driven by a rotating pool of lower-cost models, the interviewer was a deterministic agent, quality scoring was performed by a lower-cost model and cross-checked across providers, and researcher-supervised refinement was reserved for a higher-capability model. By the cost recorded in each session’s metadata, the 350 main-phase and re-administration interviews cost USD 46.95 and the logged refinement layer (probe generation, adversarial run and scoring) USD 0.64; main-phase scoring, service mapping, inter-rater runs and the classification of 7,403 pairs were not metered, so the total lies above USD 48. The provider failure reported above was detected only in the post-hoc audit, a point taken up in Section 5.6.",
 "Consistency report §9.1 items 6–7; restated analysis §11")
para("E09", "4.2", "Comparative testing across the five candidate versions",
 "Comparative testing across the five candidate versions showed that instrument structure affected the richness of the synthetic interview data modestly. Quality evaluation was conducted on the 4,816 scored question-response pairs of the 200 non-empty main transcripts, and composite richness differed significantly across versions (Kruskal–Wallis H = 22.03, p < 0.001), but within a narrow range: as summarised in Table 3, mean composite richness ranged from 3.97 (V1) to 4.12 (V3), with V4 at 4.10, and the surfacing rate of the persona-encoded latent dimensions was 98.9–99.7% for every version. Within-subject contrasts under the balanced incomplete block design favoured V2 over V1 (p = 0.013), V3 over V1 (p = 0.009) and V3 over V5 (p = 0.002), and did not separate V2 from V4 or V4 from V5.",
 "Restated analysis §3")
para("E10", "4.2", "The reliability of the scoring",
 "The reliability of the scoring was examined through multi-provider inter-rater agreement on 30 transcripts independently scored by three model providers. Six of the thirty were empty sessions on which all raters scored zero; on the 24 non-empty transcripts, agreement on composite richness was poor (ICC(2,1) = 0.14) and rank correlations between providers moderate (Spearman’s ρ 0.40–0.56). The version differences reported here are small in absolute terms and rest on a single scoring model; a new inter-rater study on non-empty transcripts is required before the scoring can be described as reliable, and the results of this section should be read with that caveat.",
 "Restated analysis §7; consistency report §9.1 item 5")
para("E11", "Table 3 caption", "Table 3. Comparative performance",
 "Table 3. Comparative performance of candidate instrument versions (non-empty main corpus; transcript-level means)", "Restated analysis §3")
for r,(n,m,ci,s,c) in enumerate([("35","3.97","3.91–4.02","99.7%","3.484"),("40","4.05","4.00–4.10","98.9%","3.528"),("38","4.12","4.07–4.18","99.4%","3.562"),("43","4.10","4.06–4.14","99.5%","3.554"),("44","4.03","3.98–4.09","99.5%","3.499")], start=1):
    for col,val in ((1,n),(2,m),(3,ci),(4,s),(5,c)): cell(f"E12.{r}.{col}", "Table 3", "Mean Richness", r, col, val, "Restated analysis §3–§4")
E.append(dict(id="E13", section="Table 3 note", kind="note_after_table", header="Mean Richness", template_prefix="Note. Question-response pairs",
 new="Note. Means of the per-transcript composite richness on the non-empty corpus (n transcripts per version as shown), with 95% intervals of ±1.96·SD/√n; the surfacing rate is the share of each persona’s encoded latent dimensions surfaced in the transcript; the composite score is the weighted ranking of Section 4.2 (quality 0.40, coverage 0.25, innovation relevance 0.20, breadth 0.15). On the full corpus, including the 100 empty sessions, the corresponding means were 2.32, 2.81, 2.64, 2.99 and 2.96.", basis="Consistency report F3; restated analysis §3"))
para("E14", "4.2", "The comparison supported the decision",
 "At the time of the study, Version 4 was carried forward on the weighted multi-criteria ranking used for version selection, which combined conversational quality (0.40), latent-dimension coverage (0.25), innovation relevance (0.20), and breadth (0.15): on the full corpus it obtained the highest composite score (2.706), ahead of Version 5 (2.565). The post-hoc audit showed that this margin reflected the distribution of empty sessions across versions. On the non-empty corpus the ranking places Version 3 first (3.562) and Version 4 second (3.554), a margin of 0.2% that does not separate them, followed by Versions 2 (3.528), 5 (3.499) and 1 (3.484); the breadth component is identical for all versions by construction. The decision to develop Version 4 therefore stands as one taken under the information then available, between two versions that the restated data do not distinguish.",
 "Restated analysis §4; consistency report §9.1 item 1")
para("E15", "4.2", "Taken together, the comparative stage",
 "Taken together, the comparative stage established that different instrument structures produced measurably, if modestly, different levels of synthetic conversational yield and markedly different insight yields (Section 4.4.1). It thereby indicated that the design of the interview guide shaped the type and quality of user knowledge that could be generated, and it provided the basis on which Version 4 was advanced to the revision and consolidation phase.",
 "Restated analysis §3, §8")
para("E16", "4.3", "A central result of the study was",
 "A central aim of the study was the identification of blind spots in the candidate instruments. For each of the twelve canonical latent dimensions tracked across the study, the coverage analysis computed the proportion of transcripts in which the dimension was surfaced. The post-hoc audit of the laboratory’s logs showed that this analysis was constrained by its own measurement design: the personas encoded nine latent dimensions (Section 3.2.1), the scoring model was shown those nine and asked which of them a response made visible, and the coverage matrix then counted the twelve canonical names. As a consequence, the six canonical dimensions that the personas encoded — identity tensions, structural barriers, power dynamics, informal care networks, autonomy versus dependence, and trust and distrust (recorded under an alias that the original matrix did not recognise) — surfaced in 95–100% of non-empty transcripts in every version, while the six canonical dimensions that no persona encoded — dignity and respect, continuity of care, partner role, digital information seeking, body image autonomy, and intergenerational patterns — were never offered to the scoring model and cannot be assessed from this corpus.",
 "Consistency report §9.1 item 3; restated analysis §5")
para("E17", "4.3", "The scale of these gaps was substantial",
 "The original diagnostics, computed on the full corpus before the audit, had reported mean surfacing per version of 27.4% (V1) to 33.9% (V4), seven blind spots in each version, and five dimensions absent from every V4 transcript. Those figures were the joint product of the empty sessions and of the encoding mismatch: the seven ‘critical’ dimensions were precisely the seven the personas did not encode, trust and distrust among them under its alias. On the restated analysis there is no version-level blind spot among the encoded dimensions, and the status of the six unencoded dimensions is unknown rather than zero. Each of the seven originally flagged dimensions had nevertheless been logged with a diagnosis and a targeted probe recommendation, which became the basis of the revision reported in the next section.",
 "Restated analysis §5")
para("E18", "4.3", "These diagnostic results mattered",
 "These results matter in two ways. Methodologically, they locate the blind spot in the laboratory rather than in the guides: a synthetic coverage analysis can only detect what its personas encode and its scoring model is asked about, and both must span the dimensions the study tracks — a requirement the implementation checklist of Appendix C now carries. Procedurally, the original diagnostics still performed the bridging function described in the design: they converted transcript patterns into dimension-level signals that drove the revision reported next, even though the audit later showed those signals to be artefacts of the measurement design.",
 "Restated analysis §5, §12")
para("E19", "4.4", "Following comparative testing and diagnostic analysis",
 "Following comparative testing and the original diagnostics, the selected candidate guide (Version 4) underwent a further cycle of revision and consolidation, producing the refined instrument V4_R1. The revision comprised 38 documented changes: 33 targeted probe additions and 5 new questions, each mapped to a specific dimension flagged by the blind-spot analysis. Every change was logged with its rationale, so that the move from diagnostic signal to instrument modification remained fully traceable.",
 "Consistency report §4 (no rewording action in the audit trail)")
para("E20", "4.4", "The effect of this revision cycle was measurable",
 "The re-administration round did not, however, test the revision. V4_R1 was administered to 50 further personas (1,253 scored responses, one for each question or probe posed), and the round’s summary statistics — mean composite richness 4.09 and a surfacing rate of 98.9%, against 2.99 and 80.7% for V4 on the full corpus — were read at the time as a 36.9% improvement. The post-hoc audit established two implementation defects: the five new questions carried journey-phase labels that the stage filter of the administration code did not recognise, so none was asked, and the 33 added probes were stored under a field the interviewer does not read and beyond its three-probe limit, so none was deployed. The sessions therefore administered Version 4 verbatim, to personas voiced by a single provider with no empty output. Compared like for like with the non-empty V4 sessions (4.10; surfacing 99.5%), the round shows no difference (Mann–Whitney p = 0.83; d = −0.04). The effect of the revision on what the instrument elicits is accordingly untested in this study, and the question of which flagged dimensions it would resolve remains open.",
 "Consistency report §9.1 item 2; restated analysis §6")
para("E21", "4.4", "A final consolidation step then reduced",
 "A final consolidation step then reduced the longer instrument — 40 questions, 32 of them populated with probes — to a shorter version of 12 core questions. A first, deterministic and reproducible multi-criteria set-cover procedure applied the same selection weights used for version comparison (quality 0.40, coverage 0.25, innovation relevance 0.20, breadth 0.15) under explicit hard constraints: every journey phase had to be represented with three questions, all twelve canonical latent dimensions had to remain covered by the items’ design targets, and items flagged as intrusive or potentially biasing were excluded; overlapping items were merged and highly specific items dropped in favour of broader applicability. This selection preserved 100% of the targeted latent-dimension coverage while holding mean composite richness essentially constant (from 2.83 to 2.82). The research team then revised the selected items: two were retained verbatim, four were reworded or extended, and six were replaced by new questions addressing the dimensions the original diagnostics had flagged, with several dropped items retained as probes; the item-by-item mapping is recorded in the reproducibility package. Finally, the question sequence was adjusted so that more concrete, less sensitive issues appeared earlier and more emotionally demanding topics later, and an introductory section was added to establish rapport and empathy before delicate matters were raised.",
 "Consistency report §6; TABLE_A_PROVENANCE.md")
para("E22", "4.4", "As a result, the final guide was not only",
 "As a result, the final guide addresses the experiential domains the original diagnostics had flagged and is more coherent, feasible, and respondent-sensitive than the longer instrument; whether it elicits those domains better than its predecessors is a question for the field deployment and expert appraisal foreseen in Section 6. The revision and consolidation phase thus combined rule-based, auditable selection with researcher judgement over content, tone, sequencing, and respondent burden.",
 "Restated analysis §6, §12")
para("E23", "4.4.1", "Beyond composite richness, the synthetic transcripts",
 "Beyond composite richness, the synthetic transcripts were classified along a needs-versus-insights axis to assess the depth of the user knowledge each guide elicited. Across the non-empty corpus — the 200 main-phase sessions together with the 50 re-administration and 5 adversarial sessions — 5,841 question-response pairs were classified as need, insight or mixed (36 further pairs were off-topic or empty and are excluded from the percentages): only 1.7% expressed surface-level needs, whereas 28.1% expressed latent insights and 70.2% combined both, yielding an overall insights-to-needs ratio of 17.0. The full corpus of 7,403 pairs gives the same percentages and ratio once its 1,567 empty or off-topic pairs are excluded.",
 "Consistency report F1; restated analysis §8")
para("E24", "4.4.1", "This ratio discriminated sharply",
 "This ratio discriminated sharply between guides (Table 4): the re-administration round achieved the highest ratio (47.6), substantially above the baseline V1 (27.0) and V4 (14.8), while the adversarial stress condition (V4_ADV) collapsed to 1.0. Because the re-administration round administered Version 4 itself, on a single persona provider (Section 4.4), its ratio is best read as the insight yield of that provider’s personas under V4 rather than as an effect of refinement; the ratio was sensitive, as intended, to the adversarial conditions under which a guide was most likely to fail. Across the five versions the ratio varied more than twofold (12.6–27.0), a larger contrast than the richness scores show. The dominance of the mixed category (70.2% of classified pairs) further indicates that most exchanges combined a concrete need with a deeper underlying motivation, the pairing most useful for innovation framing.",
 "Restated analysis §8")
for r,(s,p,i,n,ratio) in enumerate([("35","919","41.1","1.5","27.0"),("40","808","29.8","2.4","12.6"),("38","796","32.9","2.4","13.6"),("43","937","19.1","1.3","14.8"),("44","1,156","28.8","1.3","22.1")], start=1):
    for col,val in ((1,s),(2,p),(3,i),(4,n),(5,ratio)): cell(f"E25.{r}.{col}", "Table 4", "Q-R pairs", r, col, val, "Restated analysis §8")
cell("E25.6.0", "Table 4", "Q-R pairs", 6, 0, "V4_R1 round (V4 as administered)", "Consistency report §9.1 item 2")
para("E26", "Table 4 note", "Note. Question-response pairs",
 "Note. Question-response pairs are formed by matching each synthetic response with the immediately preceding interviewer turn. Percentages are shares of the pairs classified as need, insight or mixed; pairs classified as off-topic or empty are excluded (36 in the non-empty corpus). This unit differs from the response-level unit used for rubric scoring, under which the same 50 re-administration sessions yield 1,253 scored responses; the two denominators are therefore not interchangeable.",
 "Consistency report F1")
para("E27", "4.4.2", "Across 110 V4 and V4_R1 transcripts",
 "Across the 93 non-empty V4 and re-administration transcripts, 3,907 unique themes were identified, and this rule was never satisfied: new themes continued to emerge throughout, with the last five original transcripts still yielding an average of 57.0 new themes each. Theme accumulation was best described by a power law (y = 82.8x^0.850; R² = 0.995), which fit the data far better than a decelerating logarithmic model (R² = 0.861), confirming that the rate of discovery was not tailing off. The re-administration round contributed 1,821 previously unseen themes, a novelty rate of 46.6%, even though it administered the same instrument (Section 4.4): fifty further sessions on one persona provider continued to open thematic territory rather than repeating earlier content, at a lower per-transcript yield than the original sessions (36.4 against 48.5 new themes per transcript; Mann–Whitney p = 0.007). Cumulatively, half of all themes had emerged by the 41st transcript and 90% by the 84th, and every milestone beyond 75% of the total was reached within the re-administration transcripts. When the original and re-administration corpora were combined, the accumulation curve remained close to linear (y = 87.8x^0.838; R² = 0.998).",
 "Restated analysis §9")
sub("E28", "5.2", "The thematic-saturation analysis reinforces this point", "the refinement round opened additional thematic territory", "the re-administration round opened additional thematic territory", "Restated analysis §9")
para("E29", "4.6", "Table 5 reports the concordance",
 "Table 5 reports the concordance between the twelve latent dimensions tracked in the laboratory and established maternal-health evidence, alongside whether each dimension was encoded in the personas and, for the encoded dimensions, its surfacing in the non-empty transcripts of the strongest candidate version (V4). Every dimension corresponds to a documented evidence base, confirming that the synthetic design space was externally grounded rather than model-generated.",
 "Restated analysis §5")
para("E30", "Table 5 caption", "Table 5. Literature concordance", "Table 5. Literature concordance of the twelve latent dimensions, persona encoding and surfacing under V4", "Restated analysis §5")
cell("E31.0.3", "Table 5", "Indicative published anchors", 0, 3, "Encoded in personas", "Restated analysis §5")
cell("E31.0.4", "Table 5", "Indicative published anchors", 0, 4, "Surfacing under V4 (non-empty transcripts)", "Restated analysis §5")
T5 = {1:("No","Not assessable (not offered to the scoring model)"),2:("Yes","100%"),3:("Yes","100%"),4:("Yes (as trust/distrust of providers)","100%"),5:("No","Not assessable"),6:("No","Not assessable"),7:("Yes","95.3%"),8:("No","Not assessable"),9:("No","Not assessable"),10:("Yes","100%"),11:("No","Not assessable"),12:("Yes","100%")}
for r,(enc,surf) in T5.items():
    cell(f"E31.{r}.3", "Table 5", "Indicative published anchors", r, 3, enc, "Restated analysis §5"); cell(f"E31.{r}.4", "Table 5", "Indicative published anchors", r, 4, surf, "Restated analysis §5")
para("E32", "4.6", "The juxtaposition in Table 5",
 "The juxtaposition in Table 5 states the warrant of the corroboration exercise, and its limit. The published literature establishes that these dimensions matter, but it cannot establish whether a particular instrument elicits them; that is the laboratory’s task, and the laboratory performs it only for the dimensions its personas encode and its scoring model is asked about. In this study those were six of the twelve; for them every candidate version elicited the dimension in nearly every non-empty transcript, so the discriminating test the design intends was not reached, and for the other six the test was not run. The discrimination-and-repair function the laboratory is designed to perform — detecting which dimensions a guide fails to elicit and verifying that a revision repairs them — is therefore specified here and exercised procedurally (Sections 4.3 and 4.4) but not demonstrated empirically; demonstrating it requires personas and a scoring frame that span all twelve dimensions and a re-administration that administers the revised items.",
 "Restated analysis §5–§6, §12")
sub("E33a", "4.6", "Table 6 summarises the codified-standards audit", "— a further, miniature instance of the discrimination-and-repair function.", "— a small instance of the detection-and-repair logic the laboratory is designed around.", "Restated analysis §12")
sub("E33b", "4.6", "Table 6 summarises the codified-standards audit", "extends both precisely where they are silent, namely quantified blind-spot detection and measured coverage repair.", "extends both where they are silent, namely quantified blind-spot detection and measured coverage repair — functions this study specifies and, as noted above, leaves to be demonstrated.", "Restated analysis §12")
sub("E34", "4.7", "These capability elements can be specified",
 "revision was triggered by latent-dimension blind spots and executed through rule-typed, individually justified changes; consolidation applied a deterministic set-cover procedure under explicit constraints; and quality judgements were governed through multi-provider triangulation, adversarial robustness testing, full audit logging, and the strict separation of synthetic and real data.",
 "revision was triggered by the blind-spot diagnostics and executed through rule-typed, individually justified changes; consolidation applied a deterministic set-cover procedure under explicit constraints followed by documented researcher revision; and quality judgements were governed through multi-provider triangulation, adversarial robustness testing, full audit logging, and the strict separation of synthetic and real data — the logging being what allowed the provider failure and the unadministered revision to be detected and the results restated.",
 "Consistency report §6, §9.1")
para("E35", "4.7", "To move from broad categories",
 "To move from broad categories to a specified configuration, the resource base can also be described by task. Interviewing was conducted by a deterministic interviewer agent that administered each instrument verbatim and probed by rule. The synthetic personas were voiced by a rotating, multi-provider pool of OpenAI, Anthropic, and Google models, one of which returned no text in its 100 main-phase sessions (Section 4.1). Quality scoring was performed by a Google gemini-3-flash model and cross-validated across providers in the inter-rater check, while the researcher-supervised refinement used a higher-capability Anthropic claude-sonnet-4-6 model. The 150 composite personas were assembled from three inputs: Synthea-derived electronic-health-record attributes, a FinePersonas personality layer, and a SNOMED pregnancy registry. The laboratory was run over two iterations—a main comparison phase and a re-administration phase—under a common five-dimension scoring rubric, with prompt logs and refinement and consolidation provenance files retained as the artefact base that made the routine inspectable, re-runnable and, in the event, auditable.",
 "Consistency report §9.1 items 1, 6")
for (r,c,val) in [(1,1,"Cost-efficient pool for persona role-play and scoring; deterministic interviewer; higher-capability model for refinement"),(1,3,"Interaction logs; interviews USD 46.95 by session metadata, scoring and classification unmetered"),(2,3,"Persona records; risk mix 96 / 30 / 24 personas (low / medium / high)"),(4,1,"Balanced incomplete block design, 60 transcripts/version; 300 + 50 + 5 = 355 sessions, of which 200 + 50 + 5 non-empty"),(5,1,"Weighted composite (.40/.25/.20/.15); blind spot defined as surfacing below 20%"),(5,3,"V3 3.562 vs V4 3.554 on the non-empty corpus (V4 2.706 vs V5 2.565 on the full corpus); blind-spot diagnostics constrained by persona encoding"),(6,1,"38 rule-typed changes, not administered in the re-administration round (implementation defects); deterministic 32-to-12 set-cover followed by documented researcher revision"),(6,2,"Intended to close blind spots; reduces burden without losing targeted breadth"),(6,3,"No measurable effect (4.10 → 4.09); targeted latent coverage held at 100% in the set-cover"),(7,3,"ICC 0.14 on non-empty transcripts (new inter-rater study required); 5/5 robustness pass; audit trail enabled detection of the provider failure and the unadministered revision")]:
    cell(f"E36.{r}.{c}", "Table 7", "What is included in the study", r, c, val, "Consistency report F2, §9.1; restated analysis §4, §6, §7, §11")
para("E37", "5.1", "The comparative results showed that different",
 "The comparative results showed that different candidate guide logics produced modestly different levels of conversational yield, no difference in the surfacing of the encoded latent dimensions, and markedly different insight yields. This last distinction is important because innovation work depends not only on identifying stated needs but also on surfacing deeper underlying insights that can reframe user problems and opportunity spaces more productively (Liedtka & Ogilvie, 2011). This matters because it shifts attention from AI as a general-purpose assistant to AI as part of a specific design process. What shaped the output was not simply the presence of AI, but the way candidate questions, probes, and journey framings were structured, tested, and revised. In this sense, the study supports the view that AI can contribute to front-end innovation not only through idea generation or data analysis but also through the design of instruments that determine which kinds of user knowledge become available.",
 "Restated analysis §3, §8")
para("E38", "5.3", "A third contribution concerns the identification",
 "A third contribution concerns the identification and governance of blind spots — including the laboratory’s own. The synthetic testing process was designed to reveal experiential domains that a guide fails to elicit, and its original diagnostics flagged trust and distrust, partner role, body image autonomy, continuity of care, and dignity and respect among others. The post-hoc audit showed that those signals were produced by the measurement design rather than by the guides: the personas did not encode six of the twelve tracked dimensions, and the scoring model was never asked about them. The finding that matters is therefore about the laboratory: a guide may appear broad or coherent at the surface while still failing to elicit critical dimensions of lived experience, but a synthetic coverage analysis can only detect such failures for the dimensions its personas encode and its judge is asked about, and that alignment must itself be audited before diagnostics are acted upon.",
 "Restated analysis §5, §12")
para("E39", "5.4", "A fourth contribution is methodological",
 "A fourth contribution is methodological. Work on synthetic users and AI-generated research artefacts has often been criticised for limited validation and unclear standards of reliability. The present study addresses this by introducing a multi-layered validation logic, and by showing what happens when it is applied to the study itself. Candidate versions were evaluated through a structured scoring framework, compared statistically, and subjected to inter-rater agreement checks across multiple providers; the guide was tested under adversarial conditions and revised through an auditable chain of changes. The same logging then made it possible, after submission, to detect that one provider had returned no text, that the inter-rater agreement rested on empty transcripts, and that the revised guide had not been administered — and to restate every affected result on the non-empty corpus. This combination of comparative testing, blind-spot diagnostics, inter-rater checks, documented revision, and post-hoc audit moves the use of synthetic users away from ad hoc experimentation and toward a reproducible, and correctable, method of instrument development.",
 "Restated analysis §12")
para("E40", "5.4", "The corroboration layer added in Section 4.6",
 "The corroboration layer added in Section 4.6 completes this validation logic and states its warrant plainly: the literature establishes that these dimensions matter, but it cannot tell whether a particular instrument elicits them; only instrument-level testing can, and only for the dimensions the testing apparatus actually measures. In this study that apparatus measured six of the twelve dimensions and found no blind spot among them, and its revision step was not carried out as designed, so the discrimination-and-repair function that the laboratory is built to perform is specified and exercised rather than demonstrated. Because every step is logged, scored, and re-runnable, both the original claim and its correction are inspectable rather than rhetorical.",
 "Restated analysis §12")
para("E41", "5.6", "At the same time, the study has clear boundary conditions",
 "At the same time, the study has clear boundary conditions. First, the context is maternity care, and although this makes the findings analytically rich, transferability to other domains remains to be examined. Second, the synthetic corpus was intentionally generative and did not converge quickly, which supports its value as a design testbed but also reinforces that it cannot replace inquiry with real users. Third, the results reflect a particular model configuration and scoring pipeline, one of whose providers failed silently; although multi-provider checks reduce single-model dependence, the inter-rater agreement observed on non-empty transcripts was poor, and the exact values may vary as models change. Finally, the capability remains dependent on researcher oversight — and, as this study’s audit shows, on run-time integrity checks that researcher oversight alone did not supply: empty model outputs, misaligned dimension labels, and an unadministered revision passed through a fully logged pipeline undetected until the logs were audited. The evidence here suggests that the responsible use of synthetic users requires not less human judgement, but more explicit and better documented human judgement, backed by automated checks that the laboratory is measuring what it claims to measure.",
 "Consistency report §9.1; restated analysis §12")
para("E42", "6", "This paper examined how AI-enabled synthetic user research can be mobilised",
 "This paper examined how AI-enabled synthetic user research can be mobilised as a front-end innovation capability for the development of a stress-tested interview guide in maternity-care user research. The study showed that synthetic personas and interview-assisted AI can be combined in a structured design laboratory through which candidate guide versions are generated, comparatively tested, diagnosed for blind spots, and consolidated through researcher-led revision — and that the laboratory’s audit trail allows its own failures to be detected and its results restated. The result was a researcher-consolidated interview guide, along with an auditable methodological record of its production, including the record of what the laboratory did not manage to test.",
 "Restated analysis §12")
sub("E43a", "6", "The paper makes three contributions. Theoretically, it conceptualises AI-enabled synthetic user research as a knowledge-creation capability at the front end", "combining comparative testing, blind-spot diagnostics, multi-rater quality assessment, adversarial robustness checks, and rule-based consolidation.", "combining comparative testing, blind-spot diagnostics, multi-rater quality assessment, adversarial robustness checks, rule-based consolidation, and post-hoc audit of the laboratory itself.", "Restated analysis §12")
sub("E43b", "6", "The paper makes three contributions. Theoretically, it conceptualises AI-enabled synthetic user research as a knowledge-creation capability at the front end", "as a relatively low-cost and auditable way", "as an auditable and, at the scale reported here, inexpensive way", "Restated analysis §11")
para("E44", "6", "Several limitations remain",
 "Several limitations remain. The study was conducted in a single empirical domain; therefore, the findings need to be interpreted with appropriate caution regarding transferability. The laboratory’s own measurement design limited what it could detect: one persona provider returned no text in a third of the main-phase sessions, the coverage analysis could assess only the six tracked dimensions that the personas encoded, the inter-rater agreement observed on non-empty transcripts was poor, and the revised guide was not administered, so that the effect of diagnostics-driven revision — the repair half of the function the laboratory is designed to perform — remains untested. In addition, although the synthetic design laboratory established an auditable instrument development process, the paper does not claim that synthetic users are substitutes for real participants. Rather, the contribution lies in demonstrating how synthetic testing can strengthen an instrument’s design before field engagement, and how its logs allow its own shortcomings to be found. Future research should re-run the coverage analysis with personas and a scoring frame that span all tracked dimensions, administer the revised guide as revised, and re-establish scoring reliability on non-empty transcripts; it should then examine how similar synthetic design laboratories perform in other service contexts and how their outputs compare under subsequent real-world use. Two natural next steps are appraisal of the consolidated guide by panels of innovation and maternity-care experts and deployment with real participants, which together would establish the transfer conditions under which synthetically developed instruments perform in the field.",
 "Restated analysis §12")
para("E45", "Declaration of generative AI", "Generative AI systems are the object",
 "Generative AI systems are the object and the instruments of this study: synthetic personas, AI-mediated interviewing, and automated quality scoring are fully described in Section 3 and were not used to generate or alter primary observed data. In addition, the explanatory conceptual diagram presented as Fig. B was produced with the assistance of a large language model-based generative AI tool (Anthropic Claude Sonnet 5), as disclosed in its caption, and the post-hoc audit of the reproducibility package and the restatement of the results on the non-empty corpus (Section 4) were carried out with the assistance of a large language model-based coding agent under author supervision, every restated figure having been verified by the authors against the logged data. The authors reviewed and edited all content produced with these tools and take full responsibility for the content of the article.",
 "Disclosure of AI-assisted audit and restatement — authors to confirm")
para("E46", "Data availability", "The study’s artefacts are preserved",
 "The study’s artefacts are preserved as a frozen, hash-verified release comprising the instruments, the 300 main-phase interview transcripts, the calibration pilot, the scoring and classification outputs, the refinement and consolidation provenance, the audit (standards_audit.py), literature-retrieval (concordance_scopus.py) and restatement (restated_nonempty_corpus.py) scripts, and the full pipeline, with SHA-256 checksums recorded for every file. An anonymised copy of this repository is made available to reviewers through a private link and will be published upon acceptance; the dataset will be deposited in a public data repository and cited in the article with a persistent identifier (DOI), in line with the journal’s research data policy. The 50 re-administration transcripts and the per-dimension fields of the post-revision layer are embargoed until data collection for a pre-registered follow-up study closes, as documented in the repository.",
 "Consistency report §5; package rebuild of 23 Aug")
for (r,c,val) in [(4,2,"Included comparative testing, revision, and robustness rounds; 100 main-phase sessions returned no text and are excluded from the analyses (Section 4.1)"),(6,2,"Intended final stress-tested guide; not administered in the re-administration round (Section 4.4)"),(7,2,"33 probe additions and 5 new questions, each mapped to a flagged dimension"),(8,1,"40 questions (32 populated with probes)")]:
    cell(f"E47.{r}.{c}", "Table 2", "Quantity / outcome", r, c, val, "Consistency report §4, §9.1 item 2")
E.append(dict(id="E48", section="Table C (Appendix C)", kind="add_row", header="Capability dimension", cells=["14. Run-time integrity checks", "Verify, before any diagnostic is acted upon, that model outputs are non-empty, that the dimensions encoded in personas and offered to the scoring model are the dimensions tracked, and that a revised instrument is the one actually administered", "Did any provider return empty outputs? Do persona encoding, judge frame and coverage matrix use the same dimension set? Do the administered questions and probes match the revised instrument?", "Empty-output report; label-alignment check; administered-instrument diff; audit log"], basis="Restated analysis §12; consistency report §9.1"))

HIGHLIGHTS = [("Diagnostics-driven revision lifted latent-dimension coverage from 80.7% to 98.9%", "Guide structure moved insight yield twofold; an audit found the revision untested"),
              ("The auditable synthetic design laboratory is replicable at negligible cost", "The auditable synthetic design laboratory is replicable and self-correcting")]
COVER = [("were used to compare five interview-guide versions, diagnose blind spots, and lift latent-dimension coverage from 80.7% to 98.9% before researcher-led consolidation of the final instrument.",
          "were used to compare five interview-guide versions and diagnose blind spots before researcher-led consolidation of the final instrument; a post-submission audit of the laboratory’s logs, reported in the manuscript, restated the comparative results on the non-empty corpus and found the revision step untested.")]

# ---------------------------------------------------------------------------------------------------------------
def set_par_text(p, text):
    if p.runs:
        p.runs[0].text = text
        for r in p.runs[1:]: r._r.getparent().remove(r._r)
    else:
        p.add_run(text)

def find_par(doc, prefix):
    hits = [p for p in doc.paragraphs if p.text.startswith(prefix)]
    if len(hits) != 1: raise SystemExit(f"prefix not unique ({len(hits)}): {prefix[:60]}")
    return hits[0]

def find_table(doc, header):
    hits = [t for t in doc.tables if header in " ".join(c.text for c in t.rows[0].cells)]
    if len(hits) != 1: raise SystemExit(f"table header not unique ({len(hits)}): {header}")
    return hits[0]

def apply(doc, edits):
    log = []
    for e in edits:
        if e["kind"] == "para":
            p = find_par(doc, e["prefix"]); old = p.text; set_par_text(p, e["new"]); log.append((e, old, e["new"]))
        elif e["kind"] == "sub":
            p = find_par(doc, e["prefix"]); old_full = p.text
            if old_full.count(e["old"]) != 1: raise SystemExit(f"substring not unique in {e['id']}")
            new_full = old_full.replace(e["old"], e["new"])
            done = False
            for r in p.runs:
                if e["old"] in r.text: r.text = r.text.replace(e["old"], e["new"]); done = True; break
            if not done: set_par_text(p, new_full)
            log.append((e, e["old"], e["new"]))
        elif e["kind"] == "cell":
            t = find_table(doc, e["header"]); c = t.rows[e["row"]].cells[e["col"]]; old = c.text
            set_par_text(c.paragraphs[0], e["new"])
            for extra in c.paragraphs[1:]: extra._p.getparent().remove(extra._p)
            log.append((e, old, e["new"]))
        elif e["kind"] == "note_after_table":
            t = find_table(doc, e["header"]); tmpl = find_par(doc, e["template_prefix"])
            newp = copy.deepcopy(tmpl._p); t._tbl.addnext(newp)
            from docx.text.paragraph import Paragraph
            P = Paragraph(newp, tmpl._parent); set_par_text(P, e["new"]); log.append((e, "(new paragraph after Table 3)", e["new"]))
        elif e["kind"] == "add_row":
            t = find_table(doc, e["header"]); last = t.rows[-1]._tr; newtr = copy.deepcopy(last); last.addnext(newtr)
            from docx.table import _Row
            row = _Row(newtr, t)
            for c, val in zip(row.cells, e["cells"]):
                set_par_text(c.paragraphs[0], val)
                for extra in c.paragraphs[1:]: extra._p.getparent().remove(extra._p)
            log.append((e, "(new row after row 13)", " | ".join(e["cells"])))
    return log

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--src", required=True); ap.add_argument("--out", required=True); ap.add_argument("--ts", required=True)
    a = ap.parse_args(); src = Path(a.src); out = Path(a.out); out.mkdir(parents=True, exist_ok=True); ts = a.ts
    pairs = [("Technovation_Anonymized_Manuscript_rev2_20260822_150132.docx", f"Technovation_Anonymized_Manuscript_rev3_{ts}.docx"),
             ("Technovation_Manuscript_with_Authors_rev2_20260822_150132.docx", f"Technovation_Manuscript_with_Authors_rev3_{ts}.docx")]
    logs = {}
    for s, d in pairs:
        doc = Document(src / s); log = apply(doc, E); doc.save(out / d); logs[d] = [(e["id"], e["section"], e["kind"], e["basis"], old, new) for e, old, new in log]
        print(f"{d}: {len(log)} edits applied")
    # Highlights and cover letter: substring edits
    hl = Document(src.parent / "done" / "Technovation_Highlights_FINAL.docx"); n = 0
    for old, new in HIGHLIGHTS:
        for p in hl.paragraphs:
            if p.text.strip() == old: set_par_text(p, new); n += 1
    if n != len(HIGHLIGHTS): raise SystemExit("highlights not matched")
    hl.save(out / f"Technovation_Highlights_rev3_{ts}.docx"); logs[f"Technovation_Highlights_rev3_{ts}.docx"] = [("H1", "Highlights", "para", "Restated analysis §8, §12", o, nw) for o, nw in HIGHLIGHTS]
    cl = Document(src / "Technovation_Cover_Letter_rev2_20260822_150132.docx"); n = 0
    for old, new in COVER:
        for p in cl.paragraphs:
            if old in p.text: set_par_text(p, p.text.replace(old, new)); n += 1
    if n != len(COVER): raise SystemExit("cover letter not matched")
    cl.save(out / f"Technovation_Cover_Letter_rev3_{ts}.docx"); logs[f"Technovation_Cover_Letter_rev3_{ts}.docx"] = [("C1", "Cover letter", "sub", "Restated analysis §12", o, nw) for o, nw in COVER]
    json.dump(logs, open(out / f"_edits_applied_{ts}.json", "w", encoding="utf8"), ensure_ascii=False, indent=1)
    with open(out / f"SHA256_corrections_20260823.txt", "w") as fh:
        for p in sorted(out.glob("*.docx")): fh.write(f"{sha(p)}  {p.name}\n")
    print("done")

if __name__ == "__main__":
    main()
