"""
build_appendix_g.py — generate Appendix G (consolidation mathematics) from the deterministic
consolidation artefacts, as Markdown and Word. This is the "mathematical part" the manuscript
§4.4 now references: the explicit decision rule, the per-item disposition, and the final guide.
"""
import json
import os
from docx import Document
from docx.shared import Pt

PROV = "data/questionnaires/consolidated/consolidation_provenance.json"
GUIDE = "data/questionnaires/consolidated/GUIDE_A_12Q.json"
OUT_MD = "docs/supplementary/appendix_g_consolidation.md"
OUT_DOCX = "docs/supplementary/appendix_g_consolidation.docx"


def main():
    prov = json.load(open(PROV, encoding="utf-8"))
    guide = json.load(open(GUIDE, encoding="utf-8"))
    w = prov["weights"]
    before, after = prov["coverage_before"], prov["coverage_after"]

    L = []
    L.append("# Appendix G — Consolidation of the Stress-Tested Guide to 12 Core Questions")
    L.append("")
    L.append("This appendix documents the deterministic, reproducible procedure that consolidated the "
             "stress-tested interview guide (V4_R1) into the final 12-question instrument (Guide A). "
             "It is generated by `src/refinement/consolidate_guide.py`; re-running that script "
             "reproduces the identical guide and the tables below.")
    L.append("")
    L.append("## G.1 Decision rule")
    L.append("")
    L.append(f"Each of the {before['n_questions']} populated stress-tested items is scored on four "
             "features and selected under an equal per-phase quota (three questions for each of "
             "preconception, pregnancy, birth, and post-partum). The weighted criterion is:")
    L.append("")
    L.append(f"- **Composite richness** (mean synthetic-corpus quality): weight **{w['quality']}**")
    L.append(f"- **Marginal latent-dimension coverage** (new dimensions added): weight **{w['coverage']}**")
    L.append(f"- **Innovation relevance** (breadth of service-gap and knowledge lenses): weight **{w['innovation']}**")
    L.append(f"- **Breadth** (latent dimensions targeted per item): weight **{w['breadth']}**")
    L.append("")
    appr = prov.get("weights_approval") or {}
    if appr:
        L.append(f"_Weighting reviewed and approved by the {appr.get('approved_by','lead author')} "
                 f"on {appr.get('approved_on','')} as a researcher-owned decision._")
        L.append("")
    L.append("These are the same weights used for candidate-version selection in Study 1, reused for "
             "consistency. Selection is greedy and deterministic: at each step the highest-scoring item "
             "whose phase quota remains open is added, ties broken by the larger gain in new dimension "
             "coverage and then by item identifier. A final repair step guarantees that every latent "
             "dimension stays covered.")
    L.append("")
    L.append("## G.2 Outcome")
    L.append("")
    L.append(f"| Metric | Stress-tested guide ({before['n_questions']} items) | Final Guide A (12 items) |")
    L.append("|---|---|---|")
    L.append(f"| Latent-dimension coverage | {before['latent_dimension_coverage_pct']}% | {after['latent_dimension_coverage_pct']}% |")
    L.append(f"| Mean composite richness | {before['mean_composite_richness']} | {after['mean_composite_richness']} |")
    L.append(f"| Core phases covered | {len(before['core_phases_covered'])}/4 | {len(after['core_phases_covered'])}/4 |")
    L.append("")
    L.append("## G.3 Selection trace")
    L.append("")
    L.append("| Step | Question | Phase | Score | New dimensions covered |")
    L.append("|---|---|---|---|---|")
    for t in prov["trace"]:
        if t.get("rank") == "repair":
            L.append(f"| repair | {t['question_id']} | {t['phase']} | — | swap in for: {t.get('reason','')} |")
        else:
            nd = ", ".join(t.get("new_dimensions_covered", [])) or "—"
            L.append(f"| {t['rank']} | {t['question_id']} | {t['phase']} | {t['score']} | {nd} |")
    L.append("")
    L.append("## G.4 Disposition of every stress-tested item")
    L.append("")
    L.append("| Question | Phase | Decision | Note |")
    L.append("|---|---|---|---|")
    for p in prov["provenance"]:
        note = p.get("merged_into") and f"merged into {p['merged_into']}" or p.get("reason", "")
        L.append(f"| {p['question_id']} | {p['phase']} | **{p['decision']}** | {note} |")
    L.append("")
    L.append("## G.5 Final instrument (Guide A)")
    L.append("")
    phase_order = {"preconception": 0, "pregnancy": 1, "birth": 2, "postpartum": 3, "cross_phase": 4}
    qs = sorted(guide["questions"], key=lambda q: q.get("core_position", 99))
    for q in qs:
        L.append(f"**Q{q.get('core_position')} [{q.get('journey_phase')}].** {q.get('question_text','').strip()}")
        dims = sorted(set(q.get("target_latent_dimensions") or []))
        if dims:
            L.append(f"  *Latent dimensions:* {', '.join(dims)}")
        L.append("")

    md = "\n".join(L)
    os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)
    open(OUT_MD, "w", encoding="utf-8").write(md)

    # minimal docx render
    doc = Document()
    for line in L:
        if line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("|"):
            doc.add_paragraph(line, style="No Spacing")
        elif line.strip():
            doc.add_paragraph(line)
    doc.save(OUT_DOCX)
    print("wrote", OUT_MD, "and", OUT_DOCX)
    print("trace steps:", len(prov["trace"]), "| disposition rows:", len(prov["provenance"]))


if __name__ == "__main__":
    main()
